version: "3.9"
services:
  kcloud-music-api:
    container_name: kcloud-music-api
    hostname: kcloud-music-api
    image: node:18
    command: /bin/sh -c "sleep infinity"
    #environment:
      #- DB_HOST=${DB_HOST}
      #- DB_DATABASE=${DB_DATABASE}
      #- DB_USER=${DB_USER}
      #- DB_PASSWORD=${DB_PASSWORD}
      #- PORT=${PORT}
      #- BUCKET_NAME=${BUCKET_NAME}
      #- BUCKET_ACCESS_KEY=${BUCKET_ACCESS_KEY}
      #- BUCKET_SECRET_KEY=${BUCKET_SECRET_KEY}
      #- BUCKET_ENDPOINT=${BUCKET_ENDPOINT}
      #- BUCKET_REGION=${BUCKET_REGION}
      #- MAXFILESIZE=${MAXFILESIZE}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ..:/workspace

  db:
    container_name: db
    hostname: db
    image: mongo:5.0.16-focal
    command: --auth --bind_ip_all
    ports:
      - ${DB_PORT}:27017
    volumes:
      - mongo_db_data:/data/db
      - mongo_configdb:/data/configdb

volumes:
  mongo_db_data:
  mongo_configdb: